### ISSUE TITLE
Can't Start the server

### ISSUE THREAD

**Issue by tismatis** [Matis-Projects/tismatis-roads#2]
### Game Informations
The Minecraft Version: **1.19.2**
Fabric-Loader Version: **0.14.9**
Fabric-API Version: **0.61.0**

### Mods Informations
Branch of the mod: **beta**
Version of the mod: **b-1.0.2**

### Bug Informations
What side is affected: **Dedicated Server**
How remake the bug: **Start the server**
Explication of the bug: **Can't start the server**
The log of the bug: `[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'tismatis-roads'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'server' provided by 'tismatis-roads'
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 7 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class net.tismatis.tismatisroads.TismatisRoadsServer cannot be cast to net.fabricmc.api.DedicatedServerModInitializer!
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:63) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 7 more
`

**Comment by tismatis** [comment]
Fixed issue at [#bc97015](https://github.com/Matis-Projects/tismatis-roads/tree/bc97015e406e7630e1adc2e2f98d7b9295b7eec0) because of the file TismatisRoadsServer in [#41be4c5](https://github.com/Matis-Projects/tismatis-roads/commit/41be4c5d4c90f4527eb2deb102bc333bab9b09fa#diff-e21d0cb72847e248fca06cd92890f0fe5d2de10b7226b6c3ed34c9fab1de8388).
